### PR TITLE
Add comments explaining everything

### PR DESCRIPTION
**Pull request by hello-smile6**
@webdev03 was confused, so I added comments on my fork to explain everything to them. Why not share that work?

### CODE REVIEW

**Comment by Quantum-Codes** [comment]
cc @Sid72020123 

Why do we need to explain our code? We didn't intend people to read the backend. We just expect people to use the existing API. The docs are adequate right?

**Comment by hello-smile6** [comment]
> cc @Sid72020123
> 
> Why do we need to explain our code? We didn't intend people to read the backend. We just expect people to use the existing API. The docs are adequate right?

I just thought you might like it.

**Comment by Quantum-Codes** [comment]
@Sid72020123 , should I close this or merge?

**Comment by Quantum-Codes** [comment]
@hello-smile6 Thanks for this PR! I'm merging this.

**Comment by Sid72020123** [comment]
Sorry for replying late...
It's good that it's merged but there was no need for comments. But It's Ok.

**Pull request merged**
